"use client";
import { useState } from "react";
import { Braces, FileWarning } from "lucide-react";
import type { ApiOkf } from "@/lib/documents";

/** Renders the real OKF v0.2 bundle produced by the backend. */
export function OkfPreview({
  okf,
  loading,
  error,
}: {
  okf: ApiOkf | null;
  loading: boolean;
  error: string;
}) {
  const files = okf ? Object.keys(okf.files).sort() : [];
  const [active, setActive] = useState<string | null>(null);
  const current = active && files.includes(active) ? active : files[0];

  if (loading)
    return (
      <div className="loading-state" role="status">
        Loading OKF bundle…
      </div>
    );
  if (error)
    return (
      <div className="notice">
        <FileWarning size={17} />
        <span>{error}</span>
      </div>
    );
  if (!okf || !files.length) return null;
  return (
    <div>
      <div className="notice success" role="status">
        <Braces size={17} />
        <span>
          <strong>OKF v{okf.version} bundle.</strong> Generated by the server and
          validated against the Open Knowledge Format.
        </span>
      </div>
      <div className="okf-files" role="tablist" aria-label="Bundle files">
        {files.map((name) => (
          <button
            key={name}
            role="tab"
            aria-selected={name === current}
            className={`okf-file-tab ${name === current ? "active" : ""}`}
            onClick={() => setActive(name)}
          >
            {name}
          </button>
        ))}
      </div>
      <div className="code-preview">
        <div className="preview-toolbar">
          <span>
            <Braces size={16} />
            {current}
          </span>
          <span>OKF v{okf.version}</span>
        </div>
        <pre>
          <code>
            {(okf.files[current] ?? "")
              .split("\n")
              .map((line, i) => (
                <span className="code-row" key={i}>
                  <span className="line-number" aria-hidden="true">
                    {i + 1}
                  </span>
                  <span>{line}</span>
                  {"\n"}
                </span>
              ))}
          </code>
        </pre>
      </div>
    </div>
  );
}
